/**
 * Types for Video Scripts Data
 * 
 * These types define the structure of scripts generated by AI for different video formats:
 * - Teleprompter Script: Full script for reading on camera
 * - Reel Script: Short-form content (30-60 seconds)
 * - Long Video Script: Detailed YouTube-style content
 */

export type ScriptTone = 'friendly' | 'professional' | 'humorous' | 'serious';

export interface TeleprompterScript {
  title: string;
  tone: ScriptTone;
  estimatedDurationSec: number;
  lines: string[];
}

export interface ReelScript {
  title: string;
  hook: string;
  bodyPoints: string[];
  outro: string;
  estimatedDurationSec: number;
}

export interface VideoSection {
  title: string;
  summary: string;
  bullets: string[];
}

export interface LongVideoScript {
  title: string;
  intro: string;
  sections: VideoSection[];
  fullScript: string;
  outro: string;
  estimatedDurationMin: number;
}

export interface ScriptsData {
  teleprompter: TeleprompterScript;
  reel: ReelScript;
  longVideo: LongVideoScript;
}

/**
 * Helper function to get tone label in Arabic
 */
export const getToneLabel = (tone: ScriptTone): string => {
  const labels: Record<ScriptTone, string> = {
    friendly: 'ودّية',
    professional: 'احترافية',
    humorous: 'مرحة',
    serious: 'جادة',
  };
  return labels[tone];
};
